### ISSUE TITLE
服务器打开了9090的防火墙,无法打开ip:9090/ui的页面

### ISSUE THREAD

**Issue by Jasonhsl** [wanhebin/clash-for-linux#104]
流程都是正常走的,
日志输出:'/root/clash-for-linux/bin/clash-linux-amd64: line 1: clash-linux-amd64-v1.13.0: command not found'
输入'netstat -tln'这个指令的时候,并看不到9090这个端口
![image](https://github.com/wanhebin/clash-for-linux/assets/90327499/18603c11-4c7d-4fcf-a627-1276395fffc2)

**Comment by wanhebin** [comment]
"日志输出:'/root/clash-for-linux/bin/clash-linux-amd64: line 1: clash-linux-amd64-v1.13.0: command not found'"
说明程序不是正常启动，请使用调试模式（bash -x start.sh）运行脚本。

**Comment by wanhebin** [comment]
第一张图片中，bin目录下的 clash-linux-amd64 显示的是一个文件，实际上他应该是一个软连接，如下图：
![image](https://github.com/wanhebin/clash-for-linux/assets/48253420/881c29ed-fcb7-4b49-89d6-f8c8c56ca2d8)、
至于为什么在你的操作系统中它成为了了一个普通文件，这个我还不太清楚原因。

临时解决办法：
```bash
cd clash-for-linux/bin
rm -f clash-linux-amd64
ln -s clash-linux-amd64-v1.13.0 clash-linux-amd64
````
在未来的迭代中，将修复此问题。

**Comment by Jasonhsl** [comment]
感谢,已经解决,重新上传了一遍bin包,就可以解决了

**Comment by wanhebin** [comment]
> 感谢,已经解决,重新上传了一遍bin包,就可以解决了

好的。
在最新的代码中，已经取消了软连接设定，start.sh 直接引用 clash 二进制程序。你可以更新后再试试。
