### ISSUE TITLE
Country.mmdb error

### ISSUE THREAD

**Issue by ho-adam** [wanhebin/clash-for-linux#105]
启动clash出现异常，日志打印如下信息：
time="2023-07-03T17:10:52+08:00" level=info msg="Can't find MMDB, start download"
time="2023-07-03T17:10:52+08:00" level=fatal msg="Initial configuration directory error: can't initial MMDB: can't download MMDB: Get \"https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb\": x509: certificate is not valid for any names, but wanted to match cdn.jsdelivr.net"

**Comment by wanhebin** [comment]
查看 #93

**Comment by ho-adam** [comment]
已解决， 谢谢
