### ISSUE TITLE
可否默认开启对ipv6的支持

### ISSUE THREAD

**Issue by wwtd** [wanhebin/clash-for-linux#106]
感谢作者大大的工作，工具用起来很流畅。
我发现现在的默认配置没开ipv6的支持，但是已经有机场提供ipv6的机器了。不做修改连接ipv6的机器是无法访问的。
我自己试了下，只要在temp/templete_config.yaml里加上
`ipv6: true`
就可以正常使用了。
作者大大考虑把ipv6支持写进默认配置吗

**Comment by wanhebin** [comment]
> 感谢作者大大的工作，工具用起来很流畅。 我发现现在的默认配置没开ipv6的支持，但是已经有机场提供ipv6的机器了。不做修改连接ipv6的机器是无法访问的。 我自己试了下，只要在temp/templete_config.yaml里加上 `ipv6: true` 就可以正常使用了。 作者大大考虑把ipv6支持写进默认配置吗

对于需要自定义的配置，一般都建议自己去修改`temp/templete_config.yaml`文件。
因为我不确定加入额外的配置后，是否会影响其他的功能。
