### ISSUE TITLE
Unable to use URL, URL address 403, should be a front-end problem, should be a request parameter problem

### ISSUE THREAD

**Issue by saber-dym** [wanhebin/clash-for-linux#108]
![image](https://github.com/wanhebin/clash-for-linux/assets/98531695/b2aec2e1-8f16-4bcc-bed1-a3e628ffc21a)
![image](https://github.com/wanhebin/clash-for-linux/assets/98531695/13e84c0a-9ae6-4e01-98b8-0c7b0baddd5d)

Is this a restriction by the service provider and how should I bypass it?

**Comment by wanhebin** [comment]
Returning status code 403, it should be restricted by the service provider. It is recommended to consult the service provider, or check the relevant documentation of the service provider.
