### ISSUE TITLE
无法认证，fail to connetct

### ISSUE THREAD

**Issue by wangjvjie** [wanhebin/clash-for-linux#109]
我从另一个服务器访问它的控制台，输入了IP地址了，并且我已经能够远程ssh连到251.246的服务器，但是还是不行
![image](https://github.com/wanhebin/clash-for-linux/assets/82298975/28d633d3-4ca9-4c3e-ae3b-dfffc215348d)

**Comment by wanhebin** [comment]
你的 API Base URL 写的有问题，结尾不要带 / ，[使用文档](https://github.com/wanhebin/clash-for-linux#clash-dashboard)里也并未在结尾处有 / 。
