### ISSUE TITLE
[怪事]自动拉取的配置文件ui生效curl无效，手动上传的配置curl生效ui无效

### ISSUE THREAD

**Issue by Satosha256** [wanhebin/clash-for-linux#110]
昨天折腾了一天，记录如下：

先是从订阅网址自动拉取的配置，检查服务端口和环境变量都是正常，但curl或者wget都连不上被墙外网。但是浏览器访问9090端口，又能看到所有节点信息，也能选择节点。

排查了半天原因，原来是配置文件不符合标准，我打开config.yaml果然没有新信息。于是用本地Mac的配置文件（同一个订阅源）手动替换。这下curl和wget外网终于生效了！但奇葩的是，ui界面又进不去了，显示404！

所以，为啥会这样？

如果我想手动更改配置要怎么做呢？比如我要选择香港节点作为代理节点。

或者，我也可以把配置文件改成符合标准的，该怎么做？有无参考。

**Comment by wanhebin** [comment]
ok，这个问题你可以通过上传本地的 clash 配置文件来解决。可以适当参考 #69

额外注意的是，由于下载配置文件的逻辑有变更，请把 start.sh 脚本中如下部分注释：
![image](https://github.com/wanhebin/clash-for-linux/assets/48253420/c852de78-f341-4e59-9cc9-6a83cbe709ee)

**Comment by Satosha256** [comment]
谢谢老大！看来我之前替换错了，不应该替换conf文件夹下的，应该安装你说的，替换temp文件夹下的clash.yaml，再注释掉那些代码，然后重新启动程序。
