### ISSUE TITLE
请问conf目录下的config.yaml和，temp目录下的config.yaml什么区别？

### ISSUE THREAD

**Issue by Satosha256** [wanhebin/clash-for-linux#111]
我发现这两个目录下都有config.yaml这个配置文件，想问有何区别？哪一个是实际生效的？
如果我要手动上传配置文件，替换哪一个更好？

p.s. 我目前手动替换的是conf下的那个，可以翻成功，但ui界面显示404 page not found

**Comment by wanhebin** [comment]
同一个问题的后续，请不要再额外打开新的 Issues，这并不利于问题的回复。
