### ISSUE TITLE
配置文件下载失败

### ISSUE THREAD

**Issue by FlowerMagpie** [wanhebin/clash-for-linux#12]
尝试用wget进行下载也失败

**Comment by FlowerMagpie** [comment]
在更改了订阅地址后，成功下载，但是又出现了新的问题

start.sh: 67: cannot create /home/casaos/temp/proxy.txt: Directory nonexistent
start.sh: 70: cannot create /home/casaos/temp/config.yaml: Directory nonexistent
start.sh: 71: cannot create /home/casaos/temp/config.yaml: Directory nonexistent
cp: cannot stat '/home/casaos/temp/config.yaml': No such file or directory
sed: can't read /home/casaos/conf/config.yaml: No such file or directory
grep: /home/casaos/conf/config.yaml: No such file or directory
start.sh: 86: [[: not found
start.sh: 89: [[: not found
-e [ERROR] Unsupported CPU Architecture！

**Comment by FlowerMagpie** [comment]
zimaboard x86 CPU: Intel Celeron Processor 'Apollo Lake' N3350

**Comment by FlowerMagpie** [comment]
uname -a : Linux CasaOS 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

**Comment by wanhebin** [comment]
当前未在 CasaOS 系统中做过测试，应该是脚本兼容性问题。

**Comment by CarlZhang18** [comment]
> 当前未在 CasaOS 系统中做过测试，应该是脚本兼容性问题。

那需要等待后续更新

**Comment by wanhebin** [comment]
在ubuntu系统中也出现类似的问题，你可以尝试下  https://github.com/wanhebin/clash-for-linux/issues/13#issuecomment-1411522402
#
