### ISSUE TITLE
修改mode为global无效，和direct效果一致。

### ISSUE THREAD

**Issue by CongAn** [wanhebin/clash-for-linux#120]
#59 
templete_config.yaml和UI上的mode都成了global，和direct效果一致。mode为rule时是正常的代理，但是因为是规则模式所以部分域名就不会被代理。
docker 虚拟机 debian 12 系统中安装。

**Comment by wanhebin** [comment]
#10
https://github.com/wanhebin/clash-for-linux/issues/10#issuecomment-1279779923

**Comment by CongAn** [comment]
@wanhebin 感谢大大，已解决。按您所说的在代理-GLOBAL（拉到底部）中选择节点就可以了。
clash-dashboard-ui的界面设计和Clash for Windows的区别比较大，使用习惯导致没找到，希望可以在项目首页特别说明下这点。
![image](https://github.com/wanhebin/clash-for-linux/assets/16128049/0e938583-bc91-4459-8537-e85ea91fc3f0)
![image](https://github.com/wanhebin/clash-for-linux/assets/16128049/860bc23b-c153-48eb-8b30-14ceec40c4cf)
