### ISSUE TITLE
manjaro 下使用proxy_on 不能打开代理

### ISSUE THREAD

**Issue by imic07** [wanhebin/clash-for-linux#133]
$ source /etc/profile.d/clash.sh
$ proxy_on

按说明都执行了，但是不能打开代理。需要再系统代理中开启代理才可以。
![image](https://github.com/wanhebin/clash-for-linux/assets/16321067/fb3ccba2-a442-474c-ab71-0a886dc5d949)

**Comment by wanhebin** [comment]
proxy_on 只是给当前终端开启代理，该配置只对当前终端有效。
浏览器中使用，需要额外配置代理。

**Comment by imic07** [comment]
@wanhebin  有没有办法通过命令去 启用系统级别的 代理配置？ 这样就不用单独打开系统设置再配置一遍。

**Comment by wanhebin** [comment]
> @wanhebin 有没有办法通过命令去 启用系统级别的 代理配置？ 这样就不用单独打开系统设置再配置一遍。

参考下这个 #27
