### ISSUE TITLE
启动后，7890 与 9090 端口均未被监听。

### ISSUE THREAD

**Issue by Takeoff0518** [wanhebin/clash-for-linux#137]
版本：[0.3.0](https://github.com/wanhebin/clash-for-linux/releases/tag/v0.3.0)

clash-for-linux 安装位置：`/opt/clash-for-linux/`

使用 `start.sh` 启动 clash，脚本并未出现报错：

```
root@ECS1307:/opt/clash-for-linux# ./start.sh
CPU architecture: x86_64

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]

正在下载Clash配置文件...
配置文件config.yaml下载成功！                              [  OK  ]

判断订阅内容是否符合clash配置文件标准:
订阅内容符合clash标准

正在启动Clash服务...
服务启动成功！                                             [  OK  ]

Clash Dashboard 访问地址: http://<ip>:9090/ui
Secret: 112233

请执行以下命令加载环境变量: source /etc/profile.d/clash.sh

请执行以下命令开启系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

root@ECS1307:/opt/clash-for-linux#
```

但是通过网页端无法连接 dashboard。

检查端口监听情况，发现两个端口都未被监听：

```
root@ECS1307:/opt/clash-for-linux# netstat -tln | grep -E '9090|789.'
root@ECS1307:/opt/clash-for-linux#
```

`proxy_on`、`proxy_off` 可以正常使用。

检查环境变量：

```
root@ECS1307:/opt/clash-for-linux# env | grep -E 'http_proxy|https_proxy'
https_proxy=http://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
```

检查 clash 进程信息，只发现了一个进程：

```
root@ECS1307:/opt/clash-for-linux# ps ax | grep clash
 136020 pts/5    S+     0:00 grep --color=auto clash
```

尝试使用重启脚本，但是提示服务关闭失败：

```
root@ECS1307:/opt/clash-for-linux# ./restart.sh
./restart.sh: line 31: [: -eq: unary operator expected
服务关闭失败！                                             [FAILED]
```

日志输出如下：

```
root@ECS1307:/opt/clash-for-linux# cat ./logs/clash.log
time="2023-08-15T21:26:22+08:00" level=fatal msg="Parse config error: yaml: line 41: did not find expected node content"
```

尝试使用 `chmod +x` 给予 `clash-linux-amd64` 权限并再次尝试，但是没有效果。

**Comment by wanhebin** [comment]
请通过`git clone https://github.com/wanhebin/clash-for-linux.git`下载最新的代码，Release已经很久没更新了。

**Comment by hacktu2020** [comment]
我在使用免费订阅节点“https://anaer.github.io/Sub/clash.yaml”时遇到了类似问题，日志报错time="2023-08-19T14:05:50+08:00" level=fatal msg="Parse config error: rules[0] [RULE-SET,advertising,REJECT] error: unsupported rule type RULE-SET"

**Comment by wanhebin** [comment]
> 我在使用免费订阅节点“[https://anaer.github.io/Sub/clash.yaml”时遇到了类似问题，日志报错time="2023-08-19T14:05:50+08:00](https://anaer.github.io/Sub/clash.yaml%E2%80%9D%E6%97%B6%E9%81%87%E5%88%B0%E4%BA%86%E7%B1%BB%E4%BC%BC%E9%97%AE%E9%A2%98%EF%BC%8C%E6%97%A5%E5%BF%97%E6%8A%A5%E9%94%99time=%222023-08-19T14:05:50+08:00)" level=fatal msg="Parse config error: rules[0] [RULE-SET,advertising,REJECT] error: unsupported rule type RULE-SET"

https://github.com/wanhebin/clash-for-linux#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by quzizii** [comment]
碰到了同样的问题，请问问题怎么解决的？
