### ISSUE TITLE
ubuntu 进到dashboard里没有节点

### ISSUE THREAD

**Issue by pwhjy** [wanhebin/clash-for-linux#14]
> > > > 什么意思？能详细说说吗？
> > > > 已经解决了，忘关了hhhh
> > 
> > 
> > 我也是这种情况欸 能说说“忘记在网络设置里使用代理”是什么吗？
> 
> 我用的是ubuntu，需要在设置里进网络然后修改代理为手动，再加上ip和端口就可以了 ![image](https://user-images.githubusercontent.com/50053654/188819798-1c57b5e5-566f-4500-9150-c344b206e948.png)

谢谢 我应该不是这个问题。我服务器在老远的地方，只有命令行...... 
但是这个应该和
```
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
export all_proxy=socks5://127.0.0.1:7890
```
效果是一样的，所以我可能不是因为这个原因.
十分感谢你的回复，谢谢！

_Originally posted by @wenyuhaokikika in https://github.com/wanhebin/clash-for-linux/issues/7#issuecomment-1239047957_

**Comment by wanhebin** [comment]
可以看下这个 [步骤正确返回结果正确，但是没有节点 #11
](https://github.com/wanhebin/clash-for-linux/issues/11)，跟你的遇到的问题有些类似

**Comment by pwhjy** [comment]
在127.0.0.1:9090/ui的面板里面填写的是http://IP:9090/ui么，这里的IP是“IP”，还是192.168.0.1这种，我看代码里面是直接输出“IP”

**Comment by wanhebin** [comment]
> 在127.0.0.1:9090/ui的面板里面填写的是[http://IP:9090/ui么，这里的IP是“IP”，还是192.168.0.1这种，我看代码里面是直接输出“IP”](http://IP:9090/ui%E4%B9%88%EF%BC%8C%E8%BF%99%E9%87%8C%E7%9A%84IP%E6%98%AF%E2%80%9CIP%E2%80%9D%EF%BC%8C%E8%BF%98%E6%98%AF192.168.0.1%E8%BF%99%E7%A7%8D%EF%BC%8C%E6%88%91%E7%9C%8B%E4%BB%A3%E7%A0%81%E9%87%8C%E9%9D%A2%E6%98%AF%E7%9B%B4%E6%8E%A5%E8%BE%93%E5%87%BA%E2%80%9CIP%E2%80%9D)

就是你服务器的IP地址，例如：192.168.xxx.xxx。

**Comment by pwhjy** [comment]
意思是本机的ip地址么（这个我试过了不行），还是vpn的ip地址，vpn的ip地址可以怎么看。

**Comment by pwhjy** [comment]
>意思是本机的ip地址么（这个我试过了不行），还是vpn的ip地址，vpn的ip地址可以怎么看。
是不是需要先修改template_config.yaml中的external-controller的配置

**Comment by wanhebin** [comment]
> 意思是本机的ip地址么（这个我试过了不行），还是vpn的ip地址，vpn的ip地址可以怎么看。

使用192.168 这样的ip，你需要确认好你的浏览器跟你的服务器在一个内网中。如果不在，请使用公网ip
