### ISSUE TITLE
如果我 linux 本来就不能 git clone 第一步安装步骤也走不下去了

### ISSUE THREAD

**Issue by mofadeyunduo** [wanhebin/clash-for-linux#143]
怎么办 家人们 有什么建议吗

**Comment by XinCheng-lee** [comment]
下载、解压

**Comment by wanhebin** [comment]
![image](https://github.com/wanhebin/clash-for-linux/assets/48253420/bcf7a315-66c3-42ae-bb90-d710fbc71393)
