### ISSUE TITLE
clash_profile_conversion.sh: line 28: echo: write error: Broken pipe

### ISSUE THREAD

**Issue by XinCheng-lee** [wanhebin/clash-for-linux#144]
判断订阅内容是否符合clash配置文件标准:
解码后的内容不符合clash标准，尝试将其转换为标准格式
/mnt/lixincheng/clash-for-linux/scripts/clash_profile_conversion.sh: **line 28: echo: write error: Broken pipe**
配置文件已成功转换成clash标准格式****

**Comment by wanhebin** [comment]
这个问题应该是在脚本中管道传输出现了异常。详细原因可以参考下 [这里](https://stackoverflow.com/questions/49664991/why-am-i-getting-cat-write-error-broken-pipe-rarely-and-not-always) 
建议你这边多次重试该脚本，如果依然存在问题，请尝试如下临时解决方案：
替换脚本 `clash-for-linux/scripts/clash_profile_conversion.sh` 第 28 行 https://github.com/wanhebin/clash-for-linux/blob/ceb967a18dc59a4e6e400d5b13863a0ebe724c32/scripts/clash_profile_conversion.sh#L28C37-L28C148
```bash
if awk '/^proxies:/{p=1} /^proxy-groups:/{g=1} /^rules:/{r=1} p&&g&&r{exit} END{if(p&&g&&r) exit 0; else exit 1}' ${Server_Dir}/temp/clash_config.yaml; then
```
