### ISSUE TITLE
arm架构的linux

### ISSUE THREAD

**Issue by chan-bing** [wanhebin/clash-for-linux#147]
M系列芯片的mac上arm版本的linux虚拟机可以用吗

**Comment by chan-bing** [comment]
还有个问题就是每次开机之后，都需要
`$ sudo bash start.sh、
$ source /etc/profile.d/clash.sh、
$ proxy_on`
来开启代理，每次结束都要
`$ sudo bash shutdown.sh、
$ proxy_off`吗

**Comment by wanhebin** [comment]
> M系列芯片的mac上arm版本的linux虚拟机可以用吗

对于PC上的虚拟机，可以通过在虚拟机中添加环境变量的方式调用PC上启动的Clash服务。例如：
Mac上Clash的端口 7890。
在虚拟机中配置环境变量：
```bash
export http_proxy=http://<Mac IP>:7890
export https_proxy=http://<Mac IP>:7890
export HTTP_PROXY=http://<Mac IP>:7890
export HTTPS_PROXY=http://<Mac IP>:7890
```

**Comment by wanhebin** [comment]
> 还有个问题就是每次开机之后，都需要 `$ sudo bash start.sh、 $ source /etc/profile.d/clash.sh、 $ proxy_on` 来开启代理，每次结束都要 `$ sudo bash shutdown.sh、 $ proxy_off`吗

参考 #80

**Comment by chan-bing** [comment]
> > M系列芯片的mac上arm版本的linux虚拟机可以用吗
> 
> 对于PC上的虚拟机，可以通过在虚拟机中添加环境变量的方式调用PC上启动的Clash服务。例如： Mac上Clash的端口 7890。 在虚拟机中配置环境变量：
> 
> ```shell
> export http_proxy=http://<Mac IP>:7890
> export https_proxy=http://<Mac IP>:7890
> export HTTP_PROXY=http://<Mac IP>:7890
> export HTTPS_PROXY=http://<Mac IP>:7890
> ```

这个意思是我只要配置mac的clash，然后在虚拟机里面添加https和http的环境变量就能让虚拟机使用mac的vpn吗

**Comment by wanhebin** [comment]
> > > M系列芯片的mac上arm版本的linux虚拟机可以用吗
> > 
> > 
> > 对于PC上的虚拟机，可以通过在虚拟机中添加环境变量的方式调用PC上启动的Clash服务。例如： Mac上Clash的端口 7890。 在虚拟机中配置环境变量：
> > ```shell
> > export http_proxy=http://<Mac IP>:7890
> > export https_proxy=http://<Mac IP>:7890
> > export HTTP_PROXY=http://<Mac IP>:7890
> > export HTTPS_PROXY=http://<Mac IP>:7890
> > ```
> 
> 这个意思是我只要配置mac的clash，然后在虚拟机里面添加https和http的环境变量就能让虚拟机使用mac的vpn吗

是的，我以前用过这种方式。你可以尝试下。

**Comment by chan-bing** [comment]
感谢大佬
