### ISSUE TITLE
在访问Clash Dashboard一直显示"Not Found"

### ISSUE THREAD

**Issue by ssuyoungwu** [wanhebin/clash-for-linux#152]
如下图：
![Snipaste_2023-09-09_11-14-42](https://github.com/wanhebin/clash-for-linux/assets/45707612/e06833ff-e293-46e2-97fe-9d36e67a2924)

这是完整的安装流程：
root@wu:~# git clone https://github.com/wanhebin/clash-for-linux.git
正克隆到 'clash-for-linux'...
remote: Enumerating objects: 793, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 793 (delta 70), reused 82 (delta 57), pack-reused 685
接收对象中: 100% (793/793), 22.62 MiB | 7.19 MiB/s, 完成.
处理 delta 中: 100% (257/257), 完成.
root@wu:~# cd clash-for-linux
root@wu:~/clash-for-linux# bash start.sh
CPU architecture: x86_64

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]

正在下载Clash配置文件...
curl: (28) Operation timed out after 10000 milliseconds with 13672 bytes received
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
配置文件config.yaml下载成功！                              [  OK  ]

判断订阅内容是否符合clash配置文件标准:
解码后的内容不符合clash标准，尝试将其转换为标准格式
配置文件已成功转换成clash标准格式

正在启动Clash服务...
服务启动成功！                                             [  OK  ]

Clash Dashboard 访问地址: http://<ip>:9090/ui
Secret: 123456

请执行以下命令加载环境变量: source /etc/profile.d/clash.sh

请执行以下命令开启系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

root@wu:~/clash-for-linux# source /etc/profile.d/clash.sh
root@wu:~/clash-for-linux# proxy_on
[√] 已开启代理
root@wu:~/clash-for-linux# netstat -tln | grep -E '9090|789.'
tcp6       0      0 :::9090                 :::*                    LISTEN     
tcp6       0      0 :::7892                 :::*                    LISTEN     
tcp6       0      0 :::7891                 :::*                    LISTEN     
tcp6       0      0 :::7890                 :::*                    LISTEN     
root@wu:~/clash-for-linux# env | grep -E 'http_proxy|https_proxy'
https_proxy=http://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
root@wu:~/clash-for-linux# Secret='123456'
root@wu:~/clash-for-linux# curl -H "Content-Type: application/json" -H "Authorization: Bearer ${Secret}" http://127.0.0.1:9090
{"hello":"clash"}

对比后我发现“tcp6       0      0 :::9090                 :::*                    LISTEN ”与教程中的“tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN”不一致，在综合了其他的issues后我觉得应该就是这个问题，但是我在Ubuntu 22.04和Debian 11.6两个系统都试过，也试过非root账号安装、更改成777权限，一直都是同样的“Not Found”，折腾了很久，不知道如何解决这个问题，希望解答，非常感谢！

**Comment by QWQ-Fxe** [comment]
我在使用过程在也出现过该问题，可能 输入ip 问题。

**Comment by wanhebin** [comment]
> 如下图： ![Snipaste_2023-09-09_11-14-42](https://user-images.githubusercontent.com/45707612/266757846-e06833ff-e293-46e2-97fe-9d36e67a2924.png)
> 
> 这是完整的安装流程： root@wu:~# git clone https://github.com/wanhebin/clash-for-linux.git 正克隆到 'clash-for-linux'... remote: Enumerating objects: 793, done. remote: Counting objects: 100% (108/108), done. remote: Compressing objects: 100% (50/50), done. remote: Total 793 (delta 70), reused 82 (delta 57), pack-reused 685 接收对象中: 100% (793/793), 22.62 MiB | 7.19 MiB/s, 完成. 处理 delta 中: 100% (257/257), 完成. root@wu:~# cd clash-for-linux root@wu:~/clash-for-linux# bash start.sh CPU architecture: x86_64
> 
> 正在检测订阅地址... Clash订阅地址可访问！ [ OK ]
> 
> 正在下载Clash配置文件... curl: (28) Operation timed out after 10000 milliseconds with 13672 bytes received curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received 配置文件config.yaml下载成功！ [ OK ]
> 
> 判断订阅内容是否符合clash配置文件标准: 解码后的内容不符合clash标准，尝试将其转换为标准格式 配置文件已成功转换成clash标准格式
> 
> 正在启动Clash服务... 服务启动成功！ [ OK ]
> 
> Clash Dashboard 访问地址: http://:9090/ui Secret: 123456
> 
> 请执行以下命令加载环境变量: source /etc/profile.d/clash.sh
> 
> 请执行以下命令开启系统代理: proxy_on
> 
> 若要临时关闭系统代理，请执行: proxy_off
> 
> root@wu:~/clash-for-linux# source /etc/profile.d/clash.sh root@wu:~/clash-for-linux# proxy_on [√] 已开启代理 root@wu:~/clash-for-linux# netstat -tln | grep -E '9090|789.' tcp6 0 0 :::9090 :::* LISTEN tcp6 0 0 :::7892 :::* LISTEN tcp6 0 0 :::7891 :::* LISTEN tcp6 0 0 :::7890 :::* LISTEN root@wu:~/clash-for-linux# env | grep -E 'http_proxy|https_proxy' https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 root@wu:~/clash-for-linux# Secret='123456' root@wu:~/clash-for-linux# curl -H "Content-Type: application/json" -H "Authorization: Bearer ${Secret}" http://127.0.0.1:9090 {"hello":"clash"}
> 
> 对比后我发现“tcp6 0 0 :::9090 :::* LISTEN ”与教程中的“tcp 0 0 127.0.0.1:9090 0.0.0.0:* LISTEN”不一致，在综合了其他的issues后我觉得应该就是这个问题，但是我在Ubuntu 22.04和Debian 11.6两个系统都试过，也试过非root账号安装、更改成777权限，一直都是同样的“Not Found”，折腾了很久，不知道如何解决这个问题，希望解答，非常感谢！

API Base URL 输入的地址结尾处不要携带 /

**Comment by ssuyoungwu** [comment]
真的就是最后一个"/"的问题，感谢感谢，已解决
