### ISSUE TITLE
问一个问题，我用root开启代理，那么我切换到其他用户后代理还生效吗？

### ISSUE THREAD

**Issue by houyushan** [wanhebin/clash-for-linux#158]
问一个问题，我用root开启代理，那么我切换到其他用户后代理还生效吗？

**Comment by wanhebin** [comment]
正常情况下，如果再root用户下可以使用，切换到其他用户也可以使用。

**Comment by houyushan** [comment]
> 正常情况下，如果再root用户下可以使用，切换到其他用户也可以使用。

好的，谢谢。
