### ISSUE TITLE
如何正确添加特定网址的路由规则

### ISSUE THREAD

**Issue by hisou** [wanhebin/clash-for-linux#16]
如果是shutdown之后重启，似乎每次重启会重新下载config.yaml，刷新里面的域名匹配规则，那难道是要在运行时添加吗？这样能即时生效吗？

**Comment by wanhebin** [comment]
你是想自己在clash配置文件中添加额外的 路由规则？

**Comment by hisou** [comment]
是的，有一些网站没有被代理，或者有一些用了不合适的规则，我想添加修改

**Comment by wanhebin** [comment]
目前还没有添加重载配置文件的功能。不过，你可以尝试以下办法：
1.关闭代理：proxy_off。
2.找到并 kill 正在运行的clash进程，可以参考 shutdown.sh 中的方式。(不要清除环境变量)
3.修改config.yaml配置文件。
4.启动clash进程：
$ cd clash-for-linux/
$ nohup ./bin/clash-linux-amd64 -d conf/config.yaml &> logs/clash.log &

**Comment by wanhebin** [comment]
最新版本已添加重启脚本。

**Comment by hisou** [comment]
新版本已成功追加规则
