### ISSUE TITLE
配置成功后从外部访问但报错未授权

### ISSUE THREAD

**Issue by dxpmaker** [wanhebin/clash-for-linux#161]
![QQ图片20230917225224](https://github.com/wanhebin/clash-for-linux/assets/60516574/94a9c90f-02a5-4eba-806d-f85ea1c53e9c)
![QQ图片20230917225247](https://github.com/wanhebin/clash-for-linux/assets/60516574/1b8b41b5-603d-4c90-b018-98c78ef39f72)
![QQ图片20230917225258](https://github.com/wanhebin/clash-for-linux/assets/60516574/9eb8daf8-f05e-4630-9c07-99e2b3845730)
是否是需要其他设置

**Comment by wanhebin** [comment]
https://github.com/wanhebin/clash-for-linux/blob/0c119aaba5f691cd8d5cc6b8752c91713ffc6d29/.env#L3C1-L3C23
尝试在 .env 文件中配置自定义的 Secret，然后重新运行程序。

**Comment by dxpmaker** [comment]
谢谢，自定义Secret后可以正常使用了
