### ISSUE TITLE
端口被人盗用

### ISSUE THREAD

**Issue by dfmjndm** [wanhebin/clash-for-linux#167]
跑了4小时，机场发邮件说调用次数过多，封禁8小时，查日志里面一堆不认识的路由，那就是被人盗刷了，由于另一台机子的某项服务只能用http才开的公网。同样http，用v2开的口子一年多了也没这样，clash的怎么才开就被苍蝇盯上了。

**Comment by dfmjndm** [comment]
大量steam api的路由，是否是别人的访问流量传到了我这边

**Comment by wanhebin** [comment]
请做好服务器安全设置，例如 服务器防火墙、云服务器安全组等规则。

**Comment by dfmjndm** [comment]
> 请做好服务器安全设置，例如 服务器防火墙、云服务器安全组等规则。

防火墙安全组已经有了，我更关注他是怎么快速发现我这个端口的，他不可能时刻扫我的全站不然fail2ban肯定能发现

**Comment by EITSxiaozhai** [comment]
这个可以看YouTube的不良林的视频。这个是Clash配置的问题。会导致7892端口或者其他端口暴露在公网上。是一个漏洞（修改配置文件即可）因为这些都是可以利用公网高级搜索搜索到。

**Comment by dfmjndm** [comment]
> 这个可以看YouTube的不良林的视频。这个是Clash配置的问题。会导致7892端口或者其他端口暴露在公网上。是一个漏洞（修改配置文件即可）因为这些都是可以利用公网高级搜索搜索到。

明明1.13版本有漏洞还用1.13做一键包，很不理解

**Comment by wanhebin** [comment]
> > 这个可以看YouTube的不良林的视频。这个是Clash配置的问题。会导致7892端口或者其他端口暴露在公网上。是一个漏洞（修改配置文件即可）因为这些都是可以利用公网高级搜索搜索到。
> 
> 明明1.13版本有漏洞还用1.13做一键包，很不理解，我反正换掉了

有需求，自己替换即可。  项目就一个人维护，没那么多时间去不停更新迭代。

**Comment by zhangshaopu** [comment]
请问如何更换版本
