### ISSUE TITLE
root账户下代理设置只有一个终端

### ISSUE THREAD

**Issue by p1aintiff** [wanhebin/clash-for-linux#169]
使用root账户启动clash，配置代理。当前终端，端口代理设置，系统代理设置正常，wget Google可行。在另一个终端env下无代理，导入source，proxy_on后代理可用。

使用普通账户发现同样问题。

希望实现所有终端一键开关系统代理

Ubuntu 22.04 server

**Comment by wanhebin** [comment]
参考下这里 #27
