### ISSUE TITLE
启动脚本获取cpu架构的命令不全

### ISSUE THREAD

**Issue by luoxmc** [wanhebin/clash-for-linux#17]
非常感谢作者提供这么好的脚本，已经成功用上了。
不过启动脚本里面获取cpu架构的命令在我的ubuntu机器上有点问题，/bin/arch 不存在，而/usr/bin/arch确是能成功获取的。
建议修改一下，/bin/arch获取不到就再用/usr/bin/arch获取一次。

**Comment by wanhebin** [comment]
ok，这个兼容性问题将在后续优化。

**Comment by wanhebin** [comment]
麻烦提供下执行脚本异常时的完整截图

**Comment by wanhebin** [comment]
> > ok，这个兼容性问题将在后续优化。
> 
> 似乎有小问题
> 
> /bot/clash-for-linux master !5 ❯ uname -m 5s root@akg 14:10:39 x86_64
> 
> 正在启动Clash服务... ./start.sh:106: no such file or directory: /bin/arch [ERROR] Unsupported CPU Architecture！

麻烦提供下执行脚本异常时的完整截图

**Comment by sanxiadaba** [comment]
> 

这是我的报错截图
![R$G2(RSD(9V1`X8 J_)E0EY](https://user-images.githubusercontent.com/79378747/220123725-22267d7b-fab5-4f54-86ac-8e62d5874afb.png)

**Comment by wanhebin** [comment]
> > 
> 
> 这是我的报错截图 ![R$G2(RSD(9V1`X8 J_)E0EY](https://user-images.githubusercontent.com/79378747/220123725-22267d7b-fab5-4f54-86ac-8e62d5874afb.png)

这个问题似乎有人遇到过，可以看下这里 #13

**Comment by sanxiadaba** [comment]
> 

感谢，已解决

**Comment by wanhebin** [comment]
“获取CPU架构命令不全”  问题已修复。
