### ISSUE TITLE
Unsupported CPU Architecture

### ISSUE THREAD

**Issue by XIAOZHUXUEJAVA** [wanhebin/clash-for-linux#19]
本人使用的是wsl2，然后cpu是AMD的，这个仓库不适用于amd的cpu吗？
然后我如果想在docker-archlinux 容器中使用，不知道是否可以

**Comment by XIAOZHUXUEJAVA** [comment]
刚才的config.yaml文件的下载问题 切换到bash之后解决了

**Comment by wanhebin** [comment]
> 刚才的config.yaml文件的下载问题 切换到bash之后解决了

如果已经解决，请在另个Issues回复并关闭

**Comment by wanhebin** [comment]
> 本人使用的是wsl2，然后cpu是AMD的，这个仓库不适用于amd的cpu吗？ 然后我如果想在docker-archlinux 容器中使用，不知道是否可以

通过 bash -x 运行脚本，并截图发出来

**Comment by XIAOZHUXUEJAVA** [comment]
目前服务已经启动，但是我是小白，无法确定自己是否可以访问外网（github google) 
我使用了ping 命令 完全丢包

**Comment by wanhebin** [comment]
> 目前服务已经启动，但是我是小白，无法确定自己是否可以访问外网（github google) 我使用了ping 命令 完全丢包

用 curl 试试

**Comment by wanhebin** [comment]
> 目前服务已经启动，但是我是小白，无法确定自己是否可以访问外网（github google) 我使用了ping 命令 完全丢包

用curl 试试，或者在Dashboard页面更换几个节点试试

**Comment by XIAOZHUXUEJAVA** [comment]
![image](https://user-images.githubusercontent.com/81864199/220624333-6c6461e0-55ec-44e7-9472-03225139a18d.png)

运行完start.sh文件后，并没有发现readme文件中所说的IP地址

![image](https://user-images.githubusercontent.com/81864199/220625150-b3583b5a-c11a-484f-927c-d942b126179f.png)

并且我的操作系统只支持命令行，没有可视化桌面。

如果比较麻烦的话，就不打扰您了

**Comment by wanhebin** [comment]
> ![image](https://user-images.githubusercontent.com/81864199/220624333-6c6461e0-55ec-44e7-9472-03225139a18d.png)
> 
> 运行完start.sh文件后，并没有发现readme文件中所说的IP地址
> 
> ![image](https://user-images.githubusercontent.com/81864199/220625150-b3583b5a-c11a-484f-927c-d942b126179f.png)
> 
> 并且我的操作系统只支持命令行，没有可视化桌面。
> 
> 如果比较麻烦的话，就不打扰您了

把9090端口暴露到公网，通过公网的方式访问

**Comment by XIAOZHUXUEJAVA** [comment]
![image](https://user-images.githubusercontent.com/81864199/220631200-93896669-0b27-41da-ad00-0e03691c54b8.png)
我之前的步骤并没有生成 API base url 还有密码 真是头疼

**Comment by wanhebin** [comment]
> ![image](https://user-images.githubusercontent.com/81864199/220631200-93896669-0b27-41da-ad00-0e03691c54b8.png) 我之前的步骤并没有生成 API base url 还有密码 真是头疼

Secret 应该是有生成的，你仔细检查下启动脚本输出的内容。
API Base URL 是 http://公网IP:9090 。

建议你详细阅读 README.md 内容
