### ISSUE TITLE
进入到UI管理界面， 在profiler页面，看不到代理选项，只有reject和derect

### ISSUE THREAD

**Issue by atzq1234** [wanhebin/clash-for-linux#20]
![image](https://user-images.githubusercontent.com/7788620/220953278-16aff79c-226f-42b2-b4f3-fc0620d777df.png)
启动都成功，proxy_on也成功； 端口也正常；

**Comment by wanhebin** [comment]
类似的问题 #11

**Comment by atzq1234** [comment]
#11 显示是有代理节点，没开防火墙；
我这是开了防火墙后，还是找不到其他节点，像上图那样，用window桌面版有很多节点。

**Comment by wanhebin** [comment]
> #11 显示是有代理节点，没开防火墙； 我这是开了防火墙后，还是找不到其他节点，像上图那样，用window桌面版有很多节点。

你需要认真看下 #11 ，主要是要检查下载下来的配置文件是否被加密。
