### ISSUE TITLE
centos 8 一切启动正常，但是请求不了 https 

### ISSUE THREAD

**Issue by illusory-love** [wanhebin/clash-for-linux#21]
使用代理请求 https 报错：

```bash
$ curl -x "http://127.0.0.1:7890" https://api.openai.com/v1/completions

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.openai.com:443
```

在mac os上安装了一个 clash 客户端，同样的代码是可以正常请求的，mac上的终端请求的结果是

```js
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
````

能找的办法，搜的资料都找过了，没解决，可以麻烦看看么，谢谢

**Comment by wanhebin** [comment]
> 使用代理请求 https 报错：
> 
> ```shell
> $ curl -x "http://127.0.0.1:7890" https://api.openai.com/v1/completions
> 
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.openai.com:443
> ```
> 
> 在mac os上安装了一个 clash 客户端，同样的代码是可以正常请求的，mac上的终端请求的结果是
> 
> ```js
> {
>     "error": {
>         "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
>         "type": "invalid_request_error",
>         "param": null,
>         "code": null
>     }
> }
> ```
> 
> 能找的办法，搜的资料都找过了，没解决，可以麻烦看看么，谢谢

我在 Rocky Linux 8.6 （完全兼容CentOS 8）系统中尝试过你的命令， 一切正常。

但通过一些测试验证，也复现了你的问题，请看下面一张截图，希望能够给你提供帮助：
![image](https://user-images.githubusercontent.com/48253420/222809429-13c80116-2ea0-4f89-8df3-ad5415a2f231.png)

**Comment by illusory-love** [comment]
> > 使用代理请求 https 报错：
> > ```shell
> > $ curl -x "http://127.0.0.1:7890" https://api.openai.com/v1/completions
> > 
> > curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.openai.com:443
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在mac os上安装了一个 clash 客户端，同样的代码是可以正常请求的，mac上的终端请求的结果是
> > ```js
> > {
> >     "error": {
> >         "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
> >         "type": "invalid_request_error",
> >         "param": null,
> >         "code": null
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 能找的办法，搜的资料都找过了，没解决，可以麻烦看看么，谢谢
> 
> 我在 Rocky Linux 8.6 （完全兼容CentOS 8）系统中尝试过你的命令， 一切正常。
> 
> 但通过一些测试验证，也复现了你的问题，请看下面一张截图，希望能够给你提供帮助： ![image](https://user-images.githubusercontent.com/48253420/222809429-13c80116-2ea0-4f89-8df3-ad5415a2f231.png)

<img width="421" alt="WeChat320fa3bc066ff0fb0460971ac9b2e790" src="https://user-images.githubusercontent.com/12709145/222901533-29981f22-5a82-4ce2-8400-671c6fe26798.png">

<img width="440" alt="WeChat20a9bfc144c1295eb5d7fc316eeb645c" src="https://user-images.githubusercontent.com/12709145/222901530-b4bfee43-6717-462c-a8a5-19cfbadbf186.png">

那就不理解了，我确定我的节点是通的，规则也改成全局的，最终还是请求不了。

谢谢了，我自己再找找原因看

**Comment by illusory-love** [comment]
> > > 使用代理请求 https 报错：
> > > ```shell
> > > $ curl -x "http://127.0.0.1:7890" https://api.openai.com/v1/completions
> > > 
> > > curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.openai.com:443
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在mac os上安装了一个 clash 客户端，同样的代码是可以正常请求的，mac上的终端请求的结果是
> > > ```js
> > > {
> > >     "error": {
> > >         "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
> > >         "type": "invalid_request_error",
> > >         "param": null,
> > >         "code": null
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 能找的办法，搜的资料都找过了，没解决，可以麻烦看看么，谢谢
> > 
> > 
> > 我在 Rocky Linux 8.6 （完全兼容CentOS 8）系统中尝试过你的命令， 一切正常。
> > 但通过一些测试验证，也复现了你的问题，请看下面一张截图，希望能够给你提供帮助： ![image](https://user-images.githubusercontent.com/48253420/222809429-13c80116-2ea0-4f89-8df3-ad5415a2f231.png)
> 
> <img alt="WeChat320fa3bc066ff0fb0460971ac9b2e790" width="421" src="https://user-images.githubusercontent.com/12709145/222901533-29981f22-5a82-4ce2-8400-671c6fe26798.png">
> 
> <img alt="WeChat20a9bfc144c1295eb5d7fc316eeb645c" width="440" src="https://user-images.githubusercontent.com/12709145/222901530-b4bfee43-6717-462c-a8a5-19cfbadbf186.png">
> 
> 那就不理解了，我确定我的节点是通的，规则也改成全局的，最终还是请求不了。
> 
> 谢谢了，我自己再找找原因看

已经找到原因了，是我原本使用的服务商不知为啥禁止访问了（换了朋友的订阅地址也用不了），然后我更换了另外一家就能用了。
