### ISSUE TITLE
失败了

### ISSUE THREAD

**Issue by coder-mtj** [wanhebin/clash-for-linux#23]
start.sh: 7: Bad substitution
start.sh: 10: source: not found
-e 
正在检测订阅地址...
Clash订阅地址可访问！ -en                                  [  OK  ]

-e 
正在下载Clash配置文件...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
配置文件config.yaml下载失败，退出启动！ -en                [FAILED]

**Comment by wanhebin** [comment]
> start.sh: 7: Bad substitution start.sh: 10: source: not found -e 正在检测订阅地址... Clash订阅地址可访问！ -en [ OK ]
> 
> -e 正在下载Clash配置文件... curl: no URL specified! curl: try 'curl --help' or 'curl --manual' for more information curl: no URL specified! curl: try 'curl --help' or 'curl --manual' for more information 配置文件config.yaml下载失败，退出启动！ -en [FAILED]

这个问题已经有很多人遇到了，报错原因请翻阅其他的 Issues。
请尝试使用 bash 替代 sh 命令运行。
