### ISSUE TITLE
source: 没有那个文件或目录: /etc/profile.d/clash.sh

### ISSUE THREAD

**Issue by ONEBUF** [wanhebin/clash-for-linux#29]
如题 kali系统
![image](https://user-images.githubusercontent.com/24307511/224657107-20991842-5c42-4e37-a966-0b4c1a09719d.png)

**Comment by ONEBUF** [comment]
root权限下执行

**Comment by StevenLi-phoenix** [comment]
我也是遇到了这个问题但是我解决了
首先在start.sh时候使用root权限
```bash
sudo bash start.sh
```
然后就可以不使用root权限的更新
```bash
source /etc/profile.d/clash.sh
```
最后再
```bash
proxy_on
```
