### ISSUE TITLE
Unsupported CPU Architecture！

### ISSUE THREAD

**Issue by woniux** [wanhebin/clash-for-linux#3]
./start.sh:行84: /bin/arch: 没有那个文件或目录
[ERROR] Unsupported CPU Architecture！

**Comment by wanhebin** [comment]
请问你是在哪个发行版的Linux操作系统下遇到此问题的？
并检查系统中是否安装了coreutils软件，如果没有请安装后重试。

**Comment by yq1ng** [comment]
ubuntu18.04也遇到了，只需修改85行为 `get_arch=\`arch\`` 即可

**Comment by woniux** [comment]
> ubuntu18.04也遇到了，只需修改85行为 `` get_arch=`arch` `` 即可

ok已解决
