### ISSUE TITLE
fail to connect的问题

### ISSUE THREAD

**Issue by chuilishi** [wanhebin/clash-for-linux#32]
![image](https://user-images.githubusercontent.com/108377487/224897704-2a2569d8-5e0a-4c71-b28e-a47bc249585c.png)

**Comment by chuilishi** [comment]
服务已经启动了，但是fail to connect

**Comment by wanhebin** [comment]
> 

![image](https://user-images.githubusercontent.com/48253420/224912570-774d7447-9cd5-499b-9f97-86c90748b43a.png)
这里的IP需要替换成真实IP，而不是 “IP” 字符
