### ISSUE TITLE
显示启动成功，但是没有进程 网页也打不开

### ISSUE THREAD

**Issue by cvpv** [wanhebin/clash-for-linux#35]
系统是centOS7

**Comment by cvpv** [comment]
[root@localhost clash-for-linux]# sudo sh start.sh

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]

正在下载Clash配置文件...
配置文件config.yaml下载成功！                              [  OK  ]

正在启动Clash服务...
服务启动成功！                                             [  OK  ]

Clash Dashboard 访问地址：http://IP:9090/ui
Secret：b&ZlKTte5OnEt2Sn

请执行以下命令加载环境变量: source /etc/profile.d/clash.sh

请执行以下命令开启系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

[root@localhost clash-for-linux]# netstat -tln | grep -E '9090|789.'
[root@localhost clash-for-linux]# env | grep -E 'http_proxy|https_proxy'

**Comment by cvpv** [comment]
下面两个检测都为空

**Comment by wanhebin** [comment]
> 

从这里可以看出是clash配置文件中的路由规则可能存在问题，请仔细核查下，或者去 [clash](https://github.com/Dreamacro/clash) 查阅资料。

**Comment by UniStart2** [comment]
我和你问题一样，请问大佬你是怎么解决的？

**Comment by wanhebin** [comment]
> 我和你问题一样，请问大佬你是怎么解决的？

尝试下这种方法：https://github.com/wanhebin/clash-for-linux/issues/25#issuecomment-1509983980
