### ISSUE TITLE
Clash Dashboard登录页面，错误提示Unauthorized！

### ISSUE THREAD

**Issue by MMPspeed** [wanhebin/clash-for-linux#36]
![image](https://user-images.githubusercontent.com/102564003/227468360-99ed1b98-408a-46be-b2ed-0c04bb836b68.png)
所有安装步骤完成后，Secret确认是正确的，但是无法登录进去，是为什么呢？

**Comment by Rto-HB** [comment]
Secret输错位置了，是API Base URL右边的短栏
