### ISSUE TITLE
内存溢出，运行一段时间后进程被杀死原因是内存溢出

### ISSUE THREAD

**Issue by rainbow-gif** [wanhebin/clash-for-linux#37]

**Comment by wanhebin** [comment]
这个问题是程序本身问题，请去 [clash](https://github.com/Dreamacro/clash) 原项目进行查询、提问。

**Comment by rainbow-gif** [comment]
十天之前没问题就是昨天程序挂了然后重启服务就这样了，直接cpu满载，内存一点点增加然后满了就直接杀死进程了

**Comment by wanhebin** [comment]
这不是我需要关注的问题。
