### ISSUE TITLE
ui界面输入信息点击add的时候报错，这个一直提示NOT FOUNT的Label(optional)选项是要填什么东西么？

### ISSUE THREAD

**Issue by woxinfeishi** [wanhebin/clash-for-linux#40]
ui界面输入信息点击add的时候报错，这个一直提示NOT FOUNT的Label(optional)选项是要填什么东西么？
![image](https://user-images.githubusercontent.com/65987364/228470137-7bfd7171-395f-4b28-b8f4-a73b2c7e027c.png)

**Comment by wanhebin** [comment]
> ui界面输入信息点击add的时候报错，这个一直提示NOT FOUNT的Label(optional)选项是要填什么东西么？ ![image](https://user-images.githubusercontent.com/65987364/228470137-7bfd7171-395f-4b28-b8f4-a73b2c7e027c.png)

API Base URL 地址栏中，URL结尾不要携带/
