### ISSUE TITLE
/vpn/clash/clash-for-linux-master/bin/clash-linux-amd64:行1: clash-linux-amd64-v1.13.0: 未找到命令

### ISSUE THREAD

**Issue by laose307** [wanhebin/clash-for-linux#46]
/vpn/clash/clash-for-linux-master/bin/clash-linux-amd64:行1: clash-linux-amd64-v1.13.0: 未找到命令

**Comment by laose307** [comment]
这个问题解决了

**Comment by Ser-MingShao** [comment]
您好，请问你这个问题怎么解决的，我跟您遇到一样的问题了
```sh
/www/wwwroot/clash-for-linux/bin/clash-linux-amd64:行1: clash-linux-amd64-v1.13.0: 未找到命令
```

**Comment by Cyz981126** [comment]
同问，怎么解决的

**Comment by wanhebin** [comment]
这个问题应该是启动程序没有执行权限导致的，我已在最新版中修复。请下载最新的代码，并重新运行。

**Comment by uloveits** [comment]
> 这个问题应该是启动程序没有执行权限导致的，我已在最新版中修复。请下载最新的代码，并重新运行。

您好 还遇到这个问题

**Comment by wanhebin** [comment]
> > 这个问题应该是启动程序没有执行权限导致的，我已在最新版中修复。请下载最新的代码，并重新运行。
> 
> 您好 还遇到这个问题

请使用 bash -x start.sh 运行脚本，然后提供输出的内容。（注意影藏订阅地址等敏感信息。）
