### ISSUE TITLE
希望以后能支持多个节点配置

### ISSUE THREAD

**Issue by dejikcp** [wanhebin/clash-for-linux#48]
希望以后能支持多个节点配置

**Comment by wanhebin** [comment]
> 希望以后能支持多个节点配置

你这里的多节点指的是什么？

**Comment by dejikcp** [comment]
可以一次性下载多个配置，并能在web端切换

**Comment by wanhebin** [comment]
本项目本身只是对clash，yacd 项目进行整合，利用脚本简单实现代理配置。
关于你上面说的功能，本项目里没有相关计划。如有需求 你可以去原项目查看，并进行适当修改。
