### ISSUE TITLE
配置文件config.yaml下载失败，试了好多方法都下载不行

### ISSUE THREAD

**Issue by neal240** [wanhebin/clash-for-linux#49]
请问可不可以修改程序跳过这一步，我在其他端已经下好了config.yaml文件

**Comment by neal240** [comment]
start.sh: 7: Bad substitution
start.sh: 10: source: not found
-e
正在检测订阅地址...
start.sh: 64: curl: not found
Clash订阅地址可访问！ -en                                  [  OK  ]

-e
正在下载Clash配置文件...
wget：未指定 URL
用法： wget [选项]... [URL]...

请尝试使用“wget --help”查看更多的选项。
配置文件config.yaml下载失败，退出启动！ -en                [FAILED]

**Comment by neal240** [comment]
root@neal:/home/clash/clash-for-linux# sh -x start.sh
start.sh: 7: Bad substitution
+ cd
+ pwd
+ Server_Dir=/root
+ source /root/.env
start.sh: 10: source: not found
+ Conf_Dir=/root/conf
+ Temp_Dir=/root/temp
+ Log_Dir=/root/logs
+ URL=
+ unset http_proxy
+ unset https_proxy
+ unset no_proxy
+ echo -e \n正在检测订阅地址...
-e
正在检测订阅地址...
+ Text1=Clash订阅地址可访问！
+ Text2=Clash订阅地址不可访问！
+ +
curl -o /dev/null+  -sReturnStatus=0 -m
 10 --connect-timeout 10+  -w[ %{http_code} 0
 -eq 0 ]
+ + break
start.sh: 64: curl: not found
+ grepif_success [23][0-9][0-9] Clash订阅地址可访问！
 Clash订阅地址不可访问！ 0
+ local ReturnStatus=0
+ [ 0 -eq 0 ]
+ action Clash订阅地址可访问！ /bin/true
+ local STRING rc
+ STRING=Clash订阅地址可访问！
+ echo -n Clash订阅地址可访问！
Clash订阅地址可访问！ + shift
+ /bin/true
+ success $Clash订阅地址可访问！
+ echo -en \033[60G[\033[1;32m  OK  \033[0;39m]\r
-en                                                        [  OK  ]
+ return 0
+ rc=0
+ echo

+ return 0
+ echo -e \n正在下载Clash配置文件...
-e
正在下载Clash配置文件...
+ Text3=配置文件config.yaml下载成功！
+ Text4=配置文件config.yaml下载失败，退出启动！
+ wget -q --no-check-certificate -O /root/temp/clash.yaml
wget：未指定 URL
用法： wget [选项]... [URL]...

请尝试使用“wget --help”查看更多的选项。
+ ReturnStatus=1
+ [ 1 -eq 0 ]
+ continue
+ if_success 配置文件config.yaml下载成功！ 配置文件config.yaml下载失败，退出启动！ 1
+ local ReturnStatus=1
+ [ 1 -eq 0 ]
+ action 配置文件config.yaml下载失败，退出启动！ /bin/false
+ local STRING rc
+ STRING=配置文件config.yaml下载失败，退出启动！
+ echo -n 配置文件config.yaml下载失败，退出启动！
配置文件config.yaml下载失败，退出启动！ + shift
+ /bin/false
+ failure $配置文件config.yaml下载失败，退出启动！
+ local rc=1
+ echo -en \033[60G[\033[1;31mFAILED\033[0;39m]\r
-en                                                        [FAILED]
+ [ -x /bin/plymouth ]
+ /bin/plymouth --details
+ return 1
+ rc=1
+ echo

+ return 1
+ exit 1

**Comment by wanhebin** [comment]
请尝试使用 bash 命令运行脚本。
