### ISSUE TITLE
配置文件下在失败

### ISSUE THREAD

**Issue by STNPSG** [wanhebin/clash-for-linux#5]
配置文件config.yaml下载失败，退出启动！ -en                [FAILED]

**Comment by wanhebin** [comment]
在确定订阅地址可以访问的情况下，请尝试修改 start.sh 脚本部分内容：

修改位置 https://github.com/wanhebin/clash-for-linux/blob/deb7d9cc45fba14d781daa59483ae1872ee67f3b/start.sh#L61

更换另一种下载方式：
wget -q -O $Temp_Dir/clash.yaml $URL
# curl -s -o $Temp_Dir/clash.yaml $URL

**Comment by wanhebin** [comment]
> 配置文件config.yaml下载失败，退出启动！ -en [FAILED]

-en [FAILED] 问题的出现，请尝试使用 bash 命令执行脚本。
