### ISSUE TITLE
cpu占用率非常高，高到卡死

### ISSUE THREAD

**Issue by 1162431386** [wanhebin/clash-for-linux#50]
又遇到运行启动脚本后，cpu占用率异常搞，感觉很不正常，尤其是在加载管理网页的时候

**Comment by wanhebin** [comment]
相似的问题[[[Bug] TUN回环，CPU和内存占用飙升](https://github.com/Dreamacro/clash/issues/2602)](https://github.com/Dreamacro/clash/issues/2602)，希望对你有帮助。

**Comment by 1162431386** [comment]
我找到问题了，是别别人连接了 大概有100个ip来蹭我的流量，导致我这边服务器性能直线下滑，能不能加个验证机制，这样可以有效防止被蹭流量

**Comment by 1162431386** [comment]
是的，我买的节点估计有问题，一登录后，来了allow lan，一下子我服务器爆了。之前的机场就没有问题。

**Comment by 1162431386** [comment]
还有方便你问下，这个是没有秘钥验证机制的是吧

**Comment by wanhebin** [comment]
> 还有方便你问下，这个是没有秘钥验证机制的是吧

UI界面有秘钥验证机制。
