### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by mcitem** [wanhebin/clash-for-linux#54]
![图片1](https://user-images.githubusercontent.com/124600270/231240130-816cb059-ca2e-45bc-b2c4-81649e9b8584.jpg)

登录ui面板显示Unauthorized
我确定我没有填错位置
API base URL 填写http://127.0.0.1:9090/
密钥填写在右侧的Secret(optional)中
然后直接点[ADD]按钮
显示Unauthorized

系统是ubuntu桌面版，用内置浏览器填写上述内容显示Unauthorized
我就用http://yacd.haishan.me/这个网址填写服务器的内网穿透地址http://example.natappfree.cc(映射本地端口9090)
依然是显示Unauthorized

图片是用内网穿透ssh服务用手机ssh工具操作的

**Comment by wanhebin** [comment]
相似的问题：https://github.com/wanhebin/clash-for-linux/issues/40#issuecomment-1489594810

**Comment by mcitem** [comment]
![Screenshot_2023-04-12-12-00-51-345_com aliyun wuying enterprise](https://user-images.githubusercontent.com/124600270/231346128-76c73538-23e8-4913-8f8b-334dd8421939.jpg)

**Comment by mcitem** [comment]
我的Secret是完全copy&paste终端输出的，所以不会出错，操作录屏已经上传bili了，https://b23.tv/TKRhCGc

**Comment by wanhebin** [comment]
请在终端通过命令调用，验证是否存在问题：
```bash
$ Secret='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
$ curl -H "Content-Type: application/json" -H "Authorization: Bearer ${Secret}" http://127.0.0.1:9090
```
正确的返回应该是`{"hello":"clash"}`；如果你的返回结果是`{"hello":"clash"}`，则说明你在UI界面输入的Secret存在问题，例如前后有空格等。

**Comment by mcitem** [comment]
![Screenshot_2023-04-13-01-02-06-803_com sonelli juicessh](https://user-images.githubusercontent.com/124600270/231530614-76ccb307-e0b6-4be6-90f0-345547082535.jpg)
返回值{"message":"Unauthorized"}

终端信息:Welcome to Alibaba Cloud Elastic Compute Service !

Last login: Thu Apr 13 00:59:51 2023 from 127.0.0.1
root@0ll1cbuuiemjmph:~# cd clash-for-linux
root@0ll1cbuuiemjmph:~/clash-for-linux# bash start.sh
/root/clash-for-linux/.env: line 1: Clash: command not found

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]
正在下载Clash配置文件...
配置文件config.yaml下载成功！                              [  OK  ]
正在启动Clash服务...
服务启动成功！                                             [  OK  ]
Clash Dashboard 访问地址：http://<ip>:9090/ui
Secret：8cd9ff01861431dcf925d981e0004009b0cc06f383fc54989fe51b8a68666c72

请执行以下命令加载环境变量: source /etc/profile.d/clash.sh

请执行以下命令开启系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

root@0ll1cbuuiemjmph:~/clash-for-linux# proxy_on
[√] 已开启代理
root@0ll1cbuuiemjmph:~/clash-for-linux# Secret='8cd9ff01861431dcf925d981e0004009b0cc06f383fc54989fe51b8a68666c72'
root@0ll1cbuuiemjmph:~/clash-for-linux# curl -H "Content-Type: application/json" -H "Authorization: Bearer ${Secret}" http://127.0.0.1:9090
{"message":"Unauthorized"}
root@0ll1cbuuiemjmph:~/clash-for-linux#

**Comment by mcitem** [comment]
![图片](https://user-images.githubusercontent.com/124600270/231531649-9163c362-b71e-4f20-8d40-1dda73c541e7.jpg)


Welcome to Alibaba Cloud Elastic Compute Service !

Last login: Thu Apr 13 00:59:51 2023 from 127.0.0.1
root@0ll1cbuuiemjmph:~# cd clash-for-linux
root@0ll1cbuuiemjmph:~/clash-for-linux# bash start.sh
/root/clash-for-linux/.env: line 1: Clash: command not found

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]
正在下载Clash配置文件...
配置文件config.yaml下载成功！                              [  OK  ]
正在启动Clash服务...
服务启动成功！                                             [  OK  ]
Clash Dashboard 访问地址：http://<ip>:9090/ui
Secret：8cd9ff01861431dcf925d981e0004009b0cc06f383fc54989fe51b8a68666c72

请执行以下命令加载环境变量: source /etc/profile.d/clash.sh

请执行以下命令开启系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

root@0ll1cbuuiemjmph:~/clash-for-linux# proxy_on
[√] 已开启代理
root@0ll1cbuuiemjmph:~/clash-for-linux# Secret='8cd9ff01861431dcf925d981e0004009b0cc06f383fc54989fe51b8a68666c72'
root@0ll1cbuuiemjmph:~/clash-for-linux# curl -H "Content-Type: application/json" -H "Authorization: Bearer ${Secret}" http://127.0.0.1:9090
{"message":"Unauthorized"}
root@0ll1cbuuiemjmph:~/clash-for-linux#

**Comment by Grand2018** [comment]
同样遇到这个问题， 
通过 http://ip:9090/ui 登录
然后立马就会跳出来，提示输入 一直循环进不去

netstat -tln | grep -E '9090|789.'

检测 只有tcp6  xxxx
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN   
这个tcp 没有，

尝试过文件夹 777全选 没用， 
看了  issues 好多都是这个，http://ip:9090/ui 登录 问题，

本小白，纯白一个~ 求大神或作者指导下，感谢

**Comment by wanhebin** [comment]
> source /etc/profile.d/clash.sh

ok，这看起来有点奇怪，我目前还没碰到这个问题。
我看到你在执行脚本 bash start.sh 后第一行返回报错 `/root/clash-for-linux/.env: line 1: Clash: command not found`，请检查下`.env`文件中的内容有没有异常，也可以通过 `bash -x start.sh` 检查脚本执行过程中有没有异常信息。
另外，在使用proxy_on，之前我没看到你执行 `source /etc/profile.d/clash.sh` 命令，请按不要跳过提示中的步鄹。
如果有新的问题，将继续在此issue中跟踪。

**Comment by wanhebin** [comment]
> ![图片](https://user-images.githubusercontent.com/124600270/231531649-9163c362-b71e-4f20-8d40-1dda73c541e7.jpg)
> 
> Welcome to Alibaba Cloud Elastic Compute Service !
> 
> Last login: Thu Apr 13 00:59:51 2023 from 127.0.0.1 root@0ll1cbuuiemjmph:~# cd clash-for-linux root@0ll1cbuuiemjmph:~/clash-for-linux# bash start.sh /root/clash-for-linux/.env: line 1: Clash: command not found
> 
> 正在检测订阅地址... Clash订阅地址可访问！ [ OK ] 正在下载Clash配置文件... 配置文件config.yaml下载成功！ [ OK ] 正在启动Clash服务... 服务启动成功！ [ OK ] Clash Dashboard 访问地址：http://:9090/ui Secret：8cd9ff01861431dcf925d981e0004009b0cc06f383fc54989fe51b8a68666c72
> 
> 请执行以下命令加载环境变量: source /etc/profile.d/clash.sh
> 
> 请执行以下命令开启系统代理: proxy_on
> 
> 若要临时关闭系统代理，请执行: proxy_off
> 
> root@0ll1cbuuiemjmph:~/clash-for-linux# proxy_on [√] 已开启代理 root@0ll1cbuuiemjmph:~/clash-for-linux# Secret='8cd9ff01861431dcf925d981e0004009b0cc06f383fc54989fe51b8a68666c72' root@0ll1cbuuiemjmph:~/clash-for-linux# curl -H "Content-Type: application/json" -H "Authorization: Bearer ${Secret}" http://127.0.0.1:9090 {"message":"Unauthorized"} root@0ll1cbuuiemjmph:~/clash-for-linux#

ok，这看起来有点奇怪，我目前还没碰到这个问题。
我看到你在执行脚本 bash start.sh 后第一行返回报错 /root/clash-for-linux/.env: line 1: Clash: command not found，请检查下.env文件中的内容有没有异常，也可以通过 bash -x start.sh 检查脚本执行过程中有没有异常信息。
另外，在使用proxy_on，之前我没看到你执行 source /etc/profile.d/clash.sh 命令，请按不要跳过提示中的步鄹。
如果有新的问题，将继续在此issue中跟踪。

**Comment by ODomWang** [comment]
你好 问题解决了吗 我也有这个问题

**Comment by UniStart2** [comment]
我也是同样的问题，请问你们解决了吗？

**Comment by mcitem** [comment]
> 我运行`sudo sh shutdown.sh`脚本关掉后重来一遍，结果又可以进去了，真的神奇 ![重新运行start.sh脚本](https://camo.githubusercontent.com/498772e2d64321af3a80c5d4e520a4ff35f0166821f2a9fe376dbf6245c4b186/68747470733a2f2f692e696d6775722e636f6d2f466b64624e37692e706e67) 我的API Base URL写的不是`http://127.0.0.1:9090`，改成了`http://<本机IP>:9090` ,不知道不是这个原因导致的问题 ![进入了Dashboard](https://camo.githubusercontent.com/186b876c1c58a05a108e601a2bd16bda4eb700247d983d31da74a040aae090f4/68747470733a2f2f692e696d6775722e636f6d2f7a414666756f782e706e67)



> 你好 问题解决了吗 我也有这个问题


@UniStart2 @ODomWang 
我解决不了，我选择转用
Shellclash了
https://github.com/juewuy/ShellClash/blob/master/README_CN.md

**Comment by OnlyWolfy** [comment]
配了2台机都可以，有一台机也是这个问题，重新git clone项目就好了。。。。

**Comment by wanhebin** [comment]
> 配了2台机都可以，有一台机也是这个问题，重新git clone项目就好了。。。。

3台服务器运行clash-for-linux 版本都一样不？每台服务器的环境一直么？

**Comment by UniStart2** [comment]
我后来又遇到了一次这个问题，不过这次翻了一下`clash.log`发现有如下问题：
```text
time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Domestic"
time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Others"
time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Proxy"
time="2023-05-08T23:23:46+08:00" level=error msg="External controller listen error: listen tcp 0.0.0.0:9090: bind: address already in use"
time="2023-05-08T23:23:47+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
```
我自己觉得可能是因为重复运行`start.sh`导致的问题，比如之前已经已经启动过一次，然后不记得启动过由启动一次，然后就出现这种问题

我自己复现试了一下，貌似就是这样容易出现这种问题

**Comment by wanhebin** [comment]
> 我后来又遇到了一次这个问题，不过这次翻了一下`clash.log`发现有如下问题：
> 
> ```
> time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Domestic"
> time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Others"
> time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider AsianTV"
> time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider GlobalTV"
> time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Proxy"
> time="2023-05-08T23:23:46+08:00" level=error msg="External controller listen error: listen tcp 0.0.0.0:9090: bind: address already in use"
> time="2023-05-08T23:23:47+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
> ```
> 
> 我自己觉得可能是因为重复运行`start.sh`导致的问题，比如之前已经已经启动过一次，然后不记得启动过又启动一次，然后就出现这种问题
> 
> 我自己复现试了一下，貌似就是这样容易出现这种问题

如果忘记了，你可以在执行 start.sh 前，执行 shutdown.sh

**Comment by UniStart2** [comment]
@wanhebin 嗯

**Comment by OnlyWolfy** [comment]
> > 我后来又遇到了一次这个问题，不过这次翻了一下`clash.log`发现有如下问题：
> > ```
> > time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Domestic"
> > time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Others"
> > time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider AsianTV"
> > time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider GlobalTV"
> > time="2023-05-08T23:23:46+08:00" level=info msg="Start initial compatible provider Proxy"
> > time="2023-05-08T23:23:46+08:00" level=error msg="External controller listen error: listen tcp 0.0.0.0:9090: bind: address already in use"
> > time="2023-05-08T23:23:47+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我自己觉得可能是因为重复运行`start.sh`导致的问题，比如之前已经已经启动过一次，然后不记得启动过又启动一次，然后就出现这种问题
> > 我自己复现试了一下，貌似就是这样容易出现这种问题
> 
> 如果忘记了，你可以在执行 start.sh 前，执行 shutdown.sh

服务器的环境和clash版本都一样，确实也看到有帖子说shutdown.sh一下就解决了

**Comment by SeasonLinCN** [comment]
我也遇到过，编辑下.env文件，自己设置一个CLASH_SECRET的值

**Comment by HaleyBG** [comment]
我自己设了个密码就好了
