### ISSUE TITLE
问 1）如何 设置 debian默认开机自动打开clash ？ 2）如何直接把机场的SS 链接更新到clash内并正常运行？

### ISSUE THREAD

**Issue by Grand2018** [wanhebin/clash-for-linux#55]
问 1）如何 设置 debian默认开机自动打开clash ？ 
项目是部署在 随身wifi上，
经常会拔来拔去，
想实现 debian 启动后就自动运行 clash 
直接就可以翻墙的效果。
——————————————————————
问 2）如何直接把机场的SS 链接更新到clash内并正常运行？
单独的机场，一件脚本后 得到 ss 链接 和 ss 参数
如何直接 通过 ss 参数
改到clash 内 并正常 运作。
——————————————————————

大神们不忙的时候可以回答下小白的这个两个提问~ 谢谢.

**Comment by wanhebin** [comment]
> 问 1）如何 设置 debian默认开机自动打开clash ？ 项目是部署在 随身wifi上， 经常会拔来拔去， 想实现 debian 启动后就自动运行 clash 直接就可以翻墙的效果。 —————————————————————— 问 2）如何直接把机场的SS 链接更新到clash内并正常运行？ 单独的机场，一件脚本后 得到 ss 链接 和 ss 参数 如何直接 通过 ss 参数 改到clash 内 并正常 运作。 ——————————————————————
> 
> 大神们不忙的时候可以回答下小白的这个两个提问~ 谢谢.

问题1，可以通过在操作系统的开机自启配置文件中配置，例如CentOS系统的 `/etc/rc.local` 中添加 如下配置：
```bash
cd clash-for-linux
bash start.sh
```

关于问题2，请自己寻找解决办法。

**Comment by Grand2018** [comment]
感谢大神抽空回复， 
问题1学习了，

这个 Secret：xxxxxxxxxxxxx 每次启动都会有新的，
问如何固定 ？（或自定义它）

**Comment by wanhebin** [comment]
> 感谢大神抽空回复， 问题1学习了，
> 
> 这个 Secret：xxxxxxxxxxxxx 每次启动都会有新的， 问如何固定 ？（或自定义它）

修改`start.sh`脚本中的 https://github.com/wanhebin/clash-for-linux/blob/47994382aef945735ce30d78e03bac534d65b0a2/start.sh#L107 这一行，把变量值改为自定义字符串。例如：
```bash
Secret="123456"
```

**Comment by Grand2018** [comment]
再次感谢大神抽空回复，
6666 已经顺利用起来了~
