### ISSUE TITLE
无法ping通

### ISSUE THREAD

**Issue by jinxiqinghuan** [wanhebin/clash-for-linux#57]
安装步骤把一切都配置好了，也通过后台选择了多个节点尝试，设置代理模式为:Global。
但是ping google.com无反应。ping百度可以。curl 谷歌可以获得返回。

**Comment by jinxiqinghuan** [comment]
好的，谢谢大佬

**Comment by jinxiqinghuan** [comment]
大佬您好，我用来做ChatGPT网站的API调用，发现无法使用代理。请问是否和我使用阿里云服务器有关呀？

**Comment by wanhebin** [comment]
> 大佬您好，我用来做ChatGPT网站的API调用，发现无法使用代理。请问是否和我使用阿里云服务器有关呀？

没这么使用过。但ChatGPT对网络限制非常严格，很多代理的节点，即使是美国、日本等都无法使用。建议在UI界面配置全局模式，且多试试一些节点。

**Comment by jinxiqinghuan** [comment]
好的，非常感谢！
