### ISSUE TITLE
服务器上使用火狐浏览器不走代理

### ISSUE THREAD

**Issue by RyanTian96** [wanhebin/clash-for-linux#58]
![image](https://user-images.githubusercontent.com/107184337/232464984-45b64d57-9e02-43ae-8acd-41fb5354071a.png)

**Comment by RyanTian96** [comment]
![image](https://user-images.githubusercontent.com/107184337/232465336-553e6d79-0ee0-4913-b12b-2affb9b2d24a.png)
如图是我curl谷歌的信息，请大佬帮忙看下

**Comment by wanhebin** [comment]
你这个不是已经可以正常访问google了吗？

**Comment by RyanTian96** [comment]
感谢大佬的回复，我在服务器上用火狐访问谷歌，发现还是无法打开，所以才有了上面的提问

**Comment by wanhebin** [comment]
在浏览器网络设置里，手动配置下代理试下：
![image](https://user-images.githubusercontent.com/48253420/232810195-3df95eca-2822-485f-b058-f6aee583a878.png)
![image](https://user-images.githubusercontent.com/48253420/232812340-ef7b0489-7c19-4cfe-b123-bdccf6640ad3.png)
