### ISSUE TITLE
订阅地址不可访问

### ISSUE THREAD

**Issue by lzxmax** [wanhebin/clash-for-linux#6]
Clash订阅地址不可访问！ -en                                [FAILED]

但是订阅链接是可以打开的

**Comment by wanhebin** [comment]
你好，麻烦你在终端执行下面的命令并把返回结果贴出来给我看下，$URL 为你的订阅地址
curl -s --head $URL | head -n 1 | grep 'HTTP/1.[01] [23]..'

**Comment by lzxmax** [comment]
<img width="631" alt="Snipaste_2022-04-19_12-38-21" src="https://user-images.githubusercontent.com/69297333/163922396-110482f0-d7c2-4cbb-ae55-1ec7e34a30ee.png">

**Comment by wanhebin** [comment]
请你吧start.sh脚本中这条命令
curl -s --head $URL | head -n 1 | grep 'HTTP/1.[01] [23]..' > /dev/null
改为
curl -o /dev/null -s -m 10 --connect-timeout 10 -w %{http_code} $URL | grep '[23][0-9][0-9]'

然后在验证下是否有问题

**Comment by wanhebin** [comment]
此问题长时间没有回复，现关闭此问题。如需要更新，请重新打开。
