### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Henry399** [wanhebin/clash-for-linux#61]
![image](https://user-images.githubusercontent.com/43178535/233525387-4499b5cb-453a-4dbb-b2fc-87005a5164ab.png)

**Comment by wanhebin** [comment]
> ![image](https://user-images.githubusercontent.com/43178535/233525387-4499b5cb-453a-4dbb-b2fc-87005a5164ab.png)

我认为这并不是我的问题。https://blog.csdn.net/dujidan/article/details/127688346
