### ISSUE TITLE
网络流量很高

### ISSUE THREAD

**Issue by WandingPace** [wanhebin/clash-for-linux#62]
![image](https://user-images.githubusercontent.com/7385793/233708771-776f08ad-0372-428f-80aa-7bc043721eac.png)
请问流量很高怎么调查

**Comment by WandingPace** [comment]
![1682149212601](https://user-images.githubusercontent.com/7385793/233770359-07decc67-68ee-426a-b967-64d09808ffd8.jpg)
一挂上代理就有很多未知的流量。

**Comment by wanhebin** [comment]
服务器安全组要设置好，否则别人就回蹭你流量。

**Comment by WandingPace** [comment]
@wanhebin  不太懂 ，是设置那个授权对象吗，刚开始玩服务器

**Comment by WandingPace** [comment]
之前加了个7890 去掉就好了，这是什么情况0.0

**Comment by wanhebin** [comment]
网络相关知识，自己抽空去云厂商的相关文档查一下吧。

**Comment by wanhebin** [comment]
> 7890

7890是代理的端口，如果暴露在公网，被扫到后，别人也可以使用。

**Comment by wanhebin** [comment]
> 之前加了个7890 去掉就好了，这是什么情况0.0

7890是代理的端口，如果暴露在公网，被扫到后，别人也可以使用。

**Comment by WandingPace** [comment]
了解了 谢谢大佬
