### ISSUE TITLE
bug很多

### ISSUE THREAD

**Issue by 2000PJL** [wanhebin/clash-for-linux#64]
重新运行start.sh后，conf/目录下的文件全部被重写，导致配置丢失，且config.yaml文件中没有相关订阅配置，且dashboard下面的页面有问题，一些js和css没有，导致无法正常渲染页面

**Comment by wanhebin** [comment]
执行start.sh后conf/目录下的文件全部被重写，目前就是这么设计的，如果不想配置被重写，需要使用restart.sh。但这样依赖订阅地址不会被更新。
dashboard页面的问题跟我无关，使用的是别人的项目。

**Comment by wanhebin** [comment]
如果你认为本项目不够友好，建议去尝试下另一个项目https://github.com/juewuy/ShellClash
