### ISSUE TITLE
代理只有DIRECT 和 REJECT

### ISSUE THREAD

**Issue by integralSF** [wanhebin/clash-for-linux#66]
看到有人说是因为temp/clash.config没有用base64解码，手动解码后如果关闭服务再启动会恢复默认，但如果选择重启服务就不会恢复，但在ui中仍然不能选择。
![图片](https://user-images.githubusercontent.com/117735059/233861235-43094ac8-fc86-4189-afad-a8f96100c2bb.png)
![图片](https://user-images.githubusercontent.com/117735059/233861275-dde1896a-c5e2-4edd-a5a0-da94dcdd0d6b.png)
实在是小白无法解决，困扰很久了。
如果愿意帮助我，将十分感谢

**Comment by wanhebin** [comment]
> 看到有人说是因为temp/clash.config没有用base64解码，手动解码后如果关闭服务再启动会恢复默认，但如果选择重启服务就不会恢复，但在ui中仍然不能选择。 ![图片](https://user-images.githubusercontent.com/117735059/233861235-43094ac8-fc86-4189-afad-a8f96100c2bb.png) ![图片](https://user-images.githubusercontent.com/117735059/233861275-dde1896a-c5e2-4edd-a5a0-da94dcdd0d6b.png) 实在是小白无法解决，困扰很久了。 如果愿意帮助我，将十分感谢

这不是标准的clash配置格式，程序无法识别。需要转换成标准格式。

**Comment by wanhebin** [comment]
最新的代码中，已加入了修复此问题的功能，请重新下载重试。

**Comment by integralSF** [comment]
> > 看到有人说是因为temp/clash.config没有用base64解码，手动解码后如果关闭服务再启动会恢复默认，但如果选择重启服务就不会恢复，但在ui中仍然不能选择。 ![图片](https://user-images.githubusercontent.com/117735059/233861235-43094ac8-fc86-4189-afad-a8f96100c2bb.png) ![图片](https://user-images.githubusercontent.com/117735059/233861275-dde1896a-c5e2-4edd-a5a0-da94dcdd0d6b.png) 实在是小白无法解决，困扰很久了。 如果愿意帮助我，将十分感谢
> 
> 这不是标准的clash配置格式，程序无法识别。需要转换成标准格式。
十分感谢回答

**Comment by integralSF** [comment]
> 最新的代码中，已加入了修复此问题的功能，请重新下载重试。

好的，谢谢
