### ISSUE TITLE
tcp端口异常

### ISSUE THREAD

**Issue by chan-bing** [wanhebin/clash-for-linux#68]
![1682498897297](https://user-images.githubusercontent.com/115219896/234521999-43c9c9f2-5be4-457f-807f-f6a5d4210dbd.png)
![1682498999347](https://user-images.githubusercontent.com/115219896/234522823-60b8c531-d34e-4888-a0da-29224567de0d.png)

我使用的是腾讯云，无论云服务器安全组上开不开放9090端口都是这样

**Comment by wanhebin** [comment]
从报错上看，它提示9090端口已经被使用了。检查服务器内部是否有其他服务器与其冲突。
解决方法：尝试修改clash监听的9090端口为其他端口，参考 #65

**Comment by wanhebin** [comment]
> time="2023-04-26T16:57:44+08:00" level=info msg="RESTful API listening at: [::]:9089" time="2023-04-26T16:57:45+08:00" level=warning msg="[CacheFile] can't open cache file: timeout" 我修改成了9089，然后重启，现在log里面有新的问题了

关闭程序，重新执行start.sh试一下

**Comment by chan-bing** [comment]
还是没有用，我需要去安全组开放9089端口吗，我的重新启动之后 我的dashboard还是ip:9090这个网站访问，ip:9089访问不了

**Comment by chan-bing** [comment]
time="2023-04-26T17:06:32+08:00" level=error msg="External controller listen error: listen tcp 0.0.0.0:9089: bind: address already in use"
time="2023-04-26T17:06:33+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
9089也被占用了，这是为啥

**Comment by wanhebin** [comment]
> time="2023-04-26T17:06:32+08:00" level=error msg="External controller listen error: listen tcp 0.0.0.0:9089: bind: address already in use" time="2023-04-26T17:06:33+08:00" level=warning msg="[CacheFile] can't open cache file: timeout" 9089也被占用了，这是为啥

同样的错误，9089端口已经被占用。请在更改配置前，先停止程序。

**Comment by chan-bing** [comment]
ubuntu@VM-4-17-ubuntu:~/Download/clash-for-linux$ sudo sh shutdown.sh
-e 
服务关闭成功，请执行以下命令关闭系统代理：proxy_off
为什么关闭的时候会有一个-e

**Comment by wanhebin** [comment]
> ubuntu@VM-4-17-ubuntu:~/Download/clash-for-linux$ sudo sh shutdown.sh -e 服务关闭成功，请执行以下命令关闭系统代理：proxy_off 为什么关闭的时候会有一个-e

使用bash运行脚本

**Comment by chan-bing** [comment]
![1682500696408](https://user-images.githubusercontent.com/115219896/234530800-54e65c7c-b2ce-4939-ae73-4ab4bf6a1ac9.png)
哥还是这样

**Comment by FengmiQingmei** [comment]
我的是centos8.2的系统，然后按照上面的关闭服务后修改9090端口为9010，然后启动后并不能通过http://ip:9010/ui访问Clash Dashboard
![image](https://user-images.githubusercontent.com/81161427/234537829-3dea4e8d-7b32-4288-91c3-09ef8861fbba.png)
按照教程服务端口应该是IPV4的TCP-9010端口，但是不知为什么这里是IPV6的TCP-9010端口

**Comment by FengmiQingmei** [comment]
你的邮件我已收到。

**Comment by chan-bing** [comment]
> 通过这种方式检测下是否能与9010通信：[#54 (comment)](https://github.com/wanhebin/clash-for-linux/issues/54#issuecomment-1505557575)

我能正常显示{"hello":"clash"}，也能通过ip:90xx的方式访问dashboard，但是tcp哪里仍然没变化
![1682503226228](https://user-images.githubusercontent.com/115219896/234541866-b2a34841-ac24-4d34-90ea-3ec4ccd26f74.png)

**Comment by FengmiQingmei** [comment]
![image](https://user-images.githubusercontent.com/81161427/234542323-3261c705-dbae-475c-9b51-a5360da14a14.png)

**Comment by wanhebin** [comment]
> > 通过这种方式检测下是否能与9010通信：[#54 (comment)](https://github.com/wanhebin/clash-for-linux/issues/54#issuecomment-1505557575)
> 
> 我能正常显示{"hello":"clash"}，也能通过ip:90xx的方式访问dashboard，但是tcp哪里仍然没变化 ![1682503226228](https://user-images.githubusercontent.com/115219896/234541866-b2a34841-ac24-4d34-90ea-3ec4ccd26f74.png)

如果可以正常使用，为什么要纠结这个呢？

**Comment by chan-bing** [comment]
> > > 通过这种方式检测下是否能与9010通信：[#54 (comment)](https://github.com/wanhebin/clash-for-linux/issues/54#issuecomment-1505557575)
> > 
> > 
> > 我能正常显示{"hello":"clash"}，也能通过ip:90xx的方式访问dashboard，但是tcp哪里仍然没变化 ![1682503226228](https://user-images.githubusercontent.com/115219896/234541866-b2a34841-ac24-4d34-90ea-3ec4ccd26f74.png)
> 
> 如果可以正常使用，为什么要纠结这个呢？

我用不了，我刚发现在谷歌浏览器里面使用ip:9066可以直接进入dashboard，里面节点有很多，但是edge浏览器里面需要手动输入url和密码，add成功后里面节点只有direct和reject

**Comment by chan-bing** [comment]
正常的显示有很多节点的配置里面mixed port是7892，Redir Port是0，而节点只有direct和reject的配置里面是mixed port是0，Redir Port是7892

**Comment by chan-bing** [comment]
已解决，感谢，我重新下了一遍最新的代码就成功了

**Comment by wanhebin** [comment]
> 已解决，感谢，我重新下了一遍最新的代码就成功了

你确认下你的clash原配置文件是否为base64编码格式

**Comment by chan-bing** [comment]
如何查看是否是base64格式

**Comment by wanhebin** [comment]
> 如何查看是否是base64格式

直接使用wget命令下载订阅链接，然后查看下载的文件内容
