### ISSUE TITLE
配置成功了，但找不到节点？

### ISSUE THREAD

**Issue by saltfish233** [wanhebin/clash-for-linux#7]
订阅链接是有效的，但dashboard里没有节点，而且也没法正常使用代理。
![image](https://user-images.githubusercontent.com/50053654/165709573-e2922892-5881-4cba-940f-0e9a0bbfbc8e.png)
![image](https://user-images.githubusercontent.com/50053654/165709741-538bdce6-a589-4a33-8685-6ea3bd696647.png)

**Comment by saltfish233** [comment]
解决了，忘记在网络设置里使用代理。

**Comment by wenyuhaokikika** [comment]
什么意思？能详细说说吗？

**Comment by saltfish233** [comment]
> 什么意思？能详细说说吗？
已经解决了，忘关了hhhh

**Comment by wenyuhaokikika** [comment]
> > 什么意思？能详细说说吗？
> > 已经解决了，忘关了hhhh

我也是这种情况欸 能说说“忘记在网络设置里使用代理”是什么吗？

**Comment by saltfish233** [comment]
> > > 什么意思？能详细说说吗？
> > > 已经解决了，忘关了hhhh
> 
> 我也是这种情况欸 能说说“忘记在网络设置里使用代理”是什么吗？

我用的是ubuntu，需要在设置里进网络然后修改代理为手动，再加上ip和端口就可以了
![image](https://user-images.githubusercontent.com/50053654/188819798-1c57b5e5-566f-4500-9150-c344b206e948.png)

**Comment by wenyuhaokikika** [comment]
> > > > 什么意思？能详细说说吗？
> > > > 已经解决了，忘关了hhhh
> > 
> > 
> > 我也是这种情况欸 能说说“忘记在网络设置里使用代理”是什么吗？
> 
> 我用的是ubuntu，需要在设置里进网络然后修改代理为手动，再加上ip和端口就可以了 ![image](https://user-images.githubusercontent.com/50053654/188819798-1c57b5e5-566f-4500-9150-c344b206e948.png)

谢谢 我应该不是这个问题。我服务器在老远的地方，只有命令行...... 
但是这个应该和
```
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
export all_proxy=socks5://127.0.0.1:7890
```
效果是一样的，所以我可能不是因为这个原因.
十分感谢你的回复，谢谢！
