### ISSUE TITLE
希望可以兼容armv8😭

### ISSUE THREAD

**Issue by YongzhengCui** [wanhebin/clash-for-linux#70]
开发板是armv8架构，下载各种东西慢死了，希望早日兼容armv8，感谢作者做出的贡献。

**Comment by wanhebin** [comment]
> 开发板是armv8架构，下载各种东西慢死了，希望早日兼容armv8，感谢作者做出的贡献。

[clash](https://github.com/Dreamacro/clash)目前还不支持armv8，只支持armv5~armv7。
