### ISSUE TITLE
下载失败，自动退出，Ubuntu22.04

### ISSUE THREAD

**Issue by 6vision** [wanhebin/clash-for-linux#71]
多次尝试不行，Ubuntu22.04系统，
![image](https://user-images.githubusercontent.com/38057450/235368786-06c120d0-7ea8-463d-9934-68c8a26ddd82.png)
![image](https://user-images.githubusercontent.com/38057450/235368838-8f70ebb2-5f94-4069-b43a-b3ff8364b224.png)

**Comment by wanhebin** [comment]
使用 `wget -q --no-check-certificate $URL` 尝试下载

**Comment by 6vision** [comment]
> 使用 `wget -q --no-check-certificate $URL` 尝试下载
已经手动编译安装了，在centos上没问题，不知道是不是unbuntu系统原因
