### ISSUE TITLE
clash启动时候报unsupported rule type RULE-SET异常，导致clash起不来

### ISSUE THREAD

**Issue by junxworks** [wanhebin/clash-for-linux#78]
异常日志：
time="2023-05-19T10:04:03+08:00" level=info msg="Start initial compatible provider PROXY"
time="2023-05-19T10:04:03+08:00" level=fatal msg="Parse config error: rules[0] [RULE-SET,applications,DIRECT] error: unsupported rule type RULE-SET"
大佬，这个问题怎么解决？

**Comment by junxworks** [comment]
# Source: https://github.com/Loyalsoldier/clash-rules
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

........

**Comment by wanhebin** [comment]
看这里 https://github.com/wanhebin/clash-for-linux#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
