### ISSUE TITLE
一切看似正常，但又ping不通

### ISSUE THREAD

**Issue by TylorWu** [wanhebin/clash-for-linux#8]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/103818678/168987852-5b0d848e-ea00-4c94-aac4-1a3c8e7cce65.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/103818678/168987899-3873814d-8178-4fe1-aba0-5b3a20adb5ca.png">
<img width="957" alt="image" src="https://user-images.githubusercontent.com/103818678/168988127-fdff9465-9470-4f37-9645-c46019079885.png">
ping

看似一起正常，就是ping不通，我少了哪一步
<img width="909" alt="image" src="https://user-images.githubusercontent.com/103818678/168988287-82c252bb-46ed-447d-b31b-2e46fbc376c7.png">

对比桌面端我觉得好像是少了 设为代理这一步吗？ 大佬看看
<img width="301" alt="image" src="https://user-images.githubusercontent.com/103818678/168988387-8c0b8587-807c-44ce-9406-40345ba25cf6.png">

**Comment by wanhebin** [comment]
在代理界面跟换几个几个可用的代理节点尝试下
![Snipaste_2022-05-18_16-19-47](https://user-images.githubusercontent.com/48253420/168992415-e2bc1d89-73d4-41e7-817f-c20ab5898f2b.png)

**Comment by TylorWu** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/103818678/168992624-b4dacdc8-cb00-4932-aeb6-81aa69f3b1c0.png">
看这个连接是直连

**Comment by wanhebin** [comment]
从你上面这个截图来看，配置的没有问题，ping www.google.com 不通是正常的，google那边应该禁止  ICMP 的请求了。你可以试下curl www.google.com

**Comment by TylorWu** [comment]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/103818678/168994178-8cf82081-11c2-4445-b8fe-a2c612fa1e8f.png">

**Comment by wanhebin** [comment]
嗯，你这个已经可以访问google了。

**Comment by wanhebin** [comment]
RULE 模式下访问国内的IP是直连的

**Comment by wanhebin** [comment]
如果也想要走节点，可以把rule设置成global

**Comment by TylorWu** [comment]
明白了，谢谢
