### ISSUE TITLE
代理无法设置开机自启，每次重启后都需要重新执行所有步骤

### ISSUE THREAD

**Issue by EmmettHan** [wanhebin/clash-for-linux#80]

**Comment by wanhebin** [comment]
开启自己，需要你自己配合脚本、命令等方式实现，可以参考这个问题的思路 #60

**Comment by hczs** [comment]
还有一种稍微麻烦一点的，把这个注册为系统服务去设置开机启动，我是用的这种方法，已完成验证，可以参考：
https://www.sunnyc.icu/articles/e343c2eb/

**Comment by MysTer1ous** [comment]
> 还有一种稍微麻烦一点的，把这个注册为系统服务去设置开机启动，我是用的这种方法，已完成验证，可以参考： https://www.sunnyc.icu/articles/e343c2eb/

谢谢，Centos7设置自动启动代理成功
