### ISSUE TITLE
[ERROR] Unsupported CPU Architecture

### ISSUE THREAD

**Issue by QiuZuowei** [wanhebin/clash-for-linux#85]
运行 start.sh 后无法启动clash服务，报错不支持CPU架构。检测到的cpu架构是amd64，和支持的x86_64有什么区别呢？
![微信图片_20230613101318](https://github.com/wanhebin/clash-for-linux/assets/101374919/1b89fa98-ba13-4e8c-8482-66ae4c6f9c33)

**Comment by wanhebin** [comment]
实际上，应是一样的，请执行这2个命令`uname -m`、`arch` 看看输出结果

**Comment by wanhebin** [comment]
已在start.sh脚本中增加了适配，你可以在闲暇之时再重新拉取代码验证下。
