### ISSUE TITLE
Sometimes there are upper case HTTPS_PROXY in env as well

### ISSUE THREAD

**Issue by liusida** [wanhebin/clash-for-linux#95]
https://github.com/wanhebin/clash-for-linux/blob/c0505cb1b887f7ec0073f226a91d2fe65c57330f/start.sh#L89

Here, we assume that:
```
$ env | grep proxy
no_proxy=localhost,127.0.0.0/8,::1
https_proxy=http://127.0.0.1:7890/
http_proxy=http://127.0.0.1:7890/
```

However, Ubuntu also like to use uppercase variables as well:
```
$ env | grep 7890
https_proxy=http://127.0.0.1:7890/
HTTPS_PROXY=http://127.0.0.1:7890/
HTTP_PROXY=http://127.0.0.1:7890/
http_proxy=http://127.0.0.1:7890/
```

so it'll be nice to unset uppercase variables as well! (This has caused me a hour to figure out!)

So I suggest to change these three lines into:
```
unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY
```
to cover the uppercase scenario.

And, again, thanks for the tools.

**Comment by wanhebin** [comment]
Ok, thanks for sharing, this will be added in subsequent iterations.

**Comment by liusida** [comment]
;D
