### ISSUE TITLE
无法启动服务,linux 版本CentOS7.6

### ISSUE THREAD

**Issue by lengleiyuan** [wanhebin/clash-for-linux#96]
![image](https://github.com/wanhebin/clash-for-linux/assets/21060790/5ad1b65b-1c6d-4011-a3d2-1fd550acd3e5)

防火墙配置也是打开9090和7890的端口的

打开 logs/clash.log 里面有一行 /home/xxxx/clash-for-linux-master/bin/clash-linux-amd64": 没有那个文件或目录

**Comment by lengleiyuan** [comment]
防火墙配置也是打开9090和7890的端口的

**Comment by wanhebin** [comment]
> ![image](https://user-images.githubusercontent.com/21060790/249023301-5ad1b65b-1c6d-4011-a3d2-1fd550acd3e5.png)
> 
> 防火墙配置也是打开9090和7890的端口的
> 
> 打开 logs/clash.log 里面有一行 /home/xxxx/clash-for-linux-master/bin/clash-linux-amd64": 没有那个文件或目录

类似得问题，确实有一些人遇到过，但我本地还未复现过这个问题。
我想，你可以使用 bash -x start.sh 以调试模式运行脚本，或许能够分析出异常原因。

**Comment by lengleiyuan** [comment]
并无发现异常，唉

**Comment by wanhebin** [comment]
> 并无发现异常，唉

麻烦提供 托敏后的 启动脚本调试日志。

**Comment by lengleiyuan** [comment]
> 

<img width="642" alt="image" src="https://github.com/wanhebin/clash-for-linux/assets/21060790/2a28323c-71a4-4936-bec3-9f8bc75a6c66">
<img width="861" alt="image" src="https://github.com/wanhebin/clash-for-linux/assets/21060790/20bc7bbc-818e-4041-a2b2-581b7b709f3f">
是start.sh上面没加上版本号导致的问题，已经处理了。

**Comment by lengleiyuan** [comment]
> > 并无发现异常，唉
> 
> 麻烦提供 托敏后的 启动脚本调试日志。
