### ISSUE TITLE
控制台页面打不开

### ISSUE THREAD

**Issue by 15334617032** [wanhebin/clash-for-linux#97]
![image](https://github.com/wanhebin/clash-for-linux/assets/59458528/1a6b9d0e-7137-4ca7-8311-58047cf3b03d)

**Comment by wanhebin** [comment]
OK，应该是你浏览器或者网络问题导致，因为我根据你提供的 ip:port ，我已成功访问。
![image](https://github.com/wanhebin/clash-for-linux/assets/48253420/3f4e6a51-a6cf-4a6c-a2b7-f68b13b89961)

**Comment by uchzmal** [comment]
> OK，应该是你浏览器或者网络问题导致，因为我根据你提供的 ip:port ，我已成功访问。 ![image](https://user-images.githubusercontent.com/48253420/249174477-3f4e6a51-a6cf-4a6c-a2b7-f68b13b89961.png)

进去之后打不开其他东西

**Comment by uchzmal** [comment]
![Screenshot_2023-06-27-22-34-48-275_mark via](https://github.com/wanhebin/clash-for-linux/assets/117048798/eed69761-b9e6-47fd-aa7a-b735ee4acbf0)
点什么都没反应

**Comment by wanhebin** [comment]
> ![Screenshot_2023-06-27-22-34-48-275_mark via](https://user-images.githubusercontent.com/117048798/249187190-eed69761-b9e6-47fd-aa7a-b735ee4acbf0.jpg) 点什么都没反应

我没太理解你说的没反应指的是什么。
这只是一个登录界面，需要添加正确的 `API Base URL` 和 `Secret` 后 并选择才行。

**Comment by 15334617032** [comment]
感谢
